package com.smarttodo.app.bot;

public enum MessageMarker {
    WELCOME,
    TASK_MENU,
    HABIT_MENU,
    CREATE_TASK,
    HOME_MENU,
    CHANGE_TASK_TITLE,
    CHANGE_TASK_DESCRIPTION,
    CHANGE_TASK_DEADLINE,
    TASK_LIST,
    HABIT_LIST,
    CHANGE_HABIT_TITLE,
    CHANGE_HABIT_DESCRIPTION,
    CHANGE_HABIT_INTERVAL,
    CHANGE_HABIT_GOAL_DATE
}
